# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10


[[main]]
  name = "R4L@HRI2021"  # A link title for your page.
  url = "event/hri2021/"  # The URL of your page.
  identifier =  "r4lhri2021"
  weight = 15  # The position of your page in the menu.

[[main]]
  name = "Call for Participation"  # A link title for your page.
  url = "event/hri2021/cfp"  # The URL of your page.
  parent =  "r4lhri2021"
  weight = 10  # The position of your page in the menu.

[[main]]
  name = "Program"  # A link title for your page.
  url = "event/hri2021/program"  # The URL of your page.
  parent =  "r4lhri2021"
  weight = 15  # The position of your page in the menu.

[[main]]
  name = "Material"  # A link title for your page.
  url = "event/hri2021/material"  # The URL of your page.
  parent =  "r4lhri2021"
  weight = 125  # The position of your page in the menu.
  hidden = true


[[main]]
  name = " Past Events"
  url = "event"
  weight = 20

[[main]]
  name = "News"
  url = "post"
  weight = 30

[[main]]
  name = "People"
  url = "people"
  weight = 40



[[main]]
  name = "Publications"
  url = "publication"
  weight = 50

#[[main]]
#  name = "Contact"
#  url = "contact"
#  weight = 60
#  hidden = true
